### ISSUE TITLE
Getting object has no attribute 'encode' error

### ISSUE THREAD

**Issue by derekyle** [snorfalorpagus/bitwarden-haveibeenpwned#1]
First, thanks so much for this script. Was just what I was looking for. But for me, it seems to run through several of my passwords successfully, then I get this error:

Traceback (most recent call last):
  File "pwned.py", line 49, in <module>
    sys.exit(main())
  File "pwned.py", line 36, in main
    password = item["login"]["password"].encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'

All my passwords were imported from LastPass previously, so I'm wondering if that has caused some of my data to be non-normal. Any ideas?

**Comment by snorfalorpagus** [comment]
Closed by #2.
